# Site settings
title: 'Aria Components'
repo: https://github.com/goodguyry/aria-components
baseurl: /AriaComponents

# Development/Serve
port: 8080

# Build settings
markdown: kramdown
highlighter: rouge
include: [_pages]
timezone: America/Los_Angeles

# kramdown settings
kramdown:
  auto_ids: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
